#!/usr/bin/env python3

import requests

r = requests.get('https://api.kraken.com/0/public/Ticker?pair=ETHEUR');
ticker = r.json()

#print('%.2f' % float(ticker['result']['XETHZEUR']['c'][0]))
print('%.2f€' % float(ticker['result']['XETHZEUR']['c'][0]))
